name: Sync TryHackMe Progress

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run THM sync script
      run: python sync_thm.py

    - name: Commit & Push changes
      env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
     git config --global user.name "github-actions"
     git config --global user.email "actions@github.com"
     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
     git add tryhackme_rooms.md
     git commit -m "Update completed THM rooms" || echo "No changes to commit"
     git push
